apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: skywatcher-db
    url: postgres:5432
    user: admin
    secureJsonData:
      password: password
    jsonData:
      # db를 여기에 넣어야 인식이 됨!
      database: skywatcher
      sslmode: "disable"
      postgresVersion: 1500 # 버전 15
      timescaledb: false
    isDefault: true # 이걸 기본 DB로 설정